#指定当前服务端口号
server:
  port: 40020
spring:
  application:
    #指定当前服务名字
    name: app-user
  cloud:
    nacos:
      #指定nacos服务端的位置（当前仅是作为一个变量罢了）  默认为localhost:8848
      server-addr: http://localhost:8848
      discovery:
        # nacos服务端位置（注册中心服务端地址的实际使用）
        server-addr: ${spring.cloud.nacos.server-addr}